### ISSUE TITLE
Github events

### ISSUE THREAD

**Issue by theetrain** [project-colophon/app#3]
Repository dashboard
- [x] show colophon file last edit date 103cafb581b7fc575ded0eba313ade353bc97978

Event hooks
- [x] When the integration is installed, scan all repos and store in database
- [x] When there is a push to master containing a colophon file, update database
- [ ] ~When a repository is created, create a PR for a colophon file if one does not exist~
- [x] When a repo gets deleted, remove entry from database

Daily cron
- [ ] ~Refine database via daily checks~

Stretch goals
- [ ] make a GitHub check for colophon validation in PRs

**Comment by ahmadnassri** [comment]
> When a repository is created, create a PR for a colophon file if one does not exist
this doesn't make sense, when the repo is first created it has no info and therefor a colophon can't be generated with any foresight.

> Refine database via daily checks
this is not needed since the system is automatically updated on `commit` events

**Comment by ahmadnassri** [comment]
closed with final issue made into it's own task: #8
